package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Udemy: Sign up user")
    void generatedTest() {
        step("Open 'https://www.udemy.com/join/signup-popup/'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set fullName 'Greta Turcotte'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set email 'your.email+fakedata28421@gmail.com'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set password 'RP4HevJHkzGyHw9'", () -> {
            step("// todo: just add selenium action");
        });

        step("Submit form", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify that user has been created and authorized", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.udemy.com/join/signup-popup/'", () ->
            open("https://www.udemy.com/join/signup-popup/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}